---
- name: install nginx
  apt: pkg=nginx state=latest

- name: add nginx config
  template:
    src: sites-available-default
    dest: /etc/nginx/sites-available/default

- name: start nginx service
  service:
    name: nginx
    state: started
    enabled: yes
