---
- name: install nginx
  apt: pkg=nginx state=latest

- name: add nginx config
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: start nginx service
  service:
    name: nginx
    state: started
    enabled: yes
