---
- name: add host config
  include_vars: mypi.yaml

- name: raspberry pi camera and weather station
  hosts: localhost
  roles:
    - { role: general, tags: ['general'] }
    - { role: camera, tags: ['camera'] }
